name: bmw_concession
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  geolocator: ^13.0.1
  fluttertoast: ^8.2.4
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  geolocator: ^14.0.2
  image_picker: ^1.1.2
  http: ^1.2.0



flutter:
  uses-material-design: true
